baseURL = "http://example.com/"
languageCode = "pl"
title = "Kariera Testera"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Janek Królikowski"
    description = "O życiu, testowaniu i .NET"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "rainbow"
    highlightLanguages = ["csharp", "javascript", "html"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Wpisy"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:yanekk86@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/yanekk/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/janek-kr%C3%B3likowski-11a82957/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/720448"
    name = "stack-overflow"
    weight = 4
