baseURL = "https://testblog.pl/"
languageCode = "pl"
title = "testblog.pl"
theme = "hyde"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Janek Królikowski"
    description = "O życiu, testowaniu i .NET"
    themeColor = "theme-base-0d"
    highlightLanguages = ["cs", "yaml"]
    
[[menu.main]]
    url = "/posts/"
    name = "Wpisy"
    weight = 2
    
[[menu.main]]
    url = "/about"
    name = "O autorze"
    weight = 3